version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/00-Starter-Seed"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-patch"]
